In [1]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("pharmacy_sales_dataset.csv")

In [6]:
df.head()

,Invoice_ID,Date,Medicine_Name,Category,Quantity,Unit_Price,Revenue,Profit,Customer_Type,Branch,Payment_Method,Stock_Available,Expiry_Date
0,INV00001,16-04-2024,Omeprazole,Vitamin,11,994.95,10944.45,2705.68,New,Hyderabad,Cash,376,07-05-2025
1,INV00002,15-04-2025,Omeprazole,Antibiotic,4,401.28,1605.12,201.31,New,Pune,UPI,163,19-04-2026
2,INV00003,20-10-2024,Azithromycin,Diabetes,18,733.21,13197.78,4196.14,Regular,Pune,Cash,129,27-02-2026
3,INV00004,02-04-2024,Calcium Tablets,Antacid,18,181.13,3260.34,372.62,New,Mumbai,UPI,376,02-01-2026
4,INV00005,09-04-2025,Aspirin,Cold & Flu,11,611.62,6727.82,1844.97,Regular,Hyderabad,UPI,24,13-03-2027

In [8]:
df.shape

(2000, 13)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Invoice_ID       2000 non-null   str
 1   Date             2000 non-null   str
 2   Medicine_Name    2000 non-null   str
 3   Category         2000 non-null   str
 4   Quantity         2000 non-null   int64
 5   Unit_Price       2000 non-null   float64
 6   Revenue          2000 non-null   float64
 7   Profit           2000 non-null   float64
 8   Customer_Type    2000 non-null   str
 9   Branch           2000 non-null   str
 10  Payment_Method   2000 non-null   str
 11  Stock_Available  2000 non-null   int64
 12  Expiry_Date      2000 non-null   str
dtypes: float64(3), int64(2), str(8)
memory usage: 203.3 KB

In [10]:
df.columns

Index(['Invoice_ID', 'Date', 'Medicine_Name', 'Category', 'Quantity',
       'Unit_Price', 'Revenue', 'Profit', 'Customer_Type', 'Branch',
       'Payment_Method', 'Stock_Available', 'Expiry_Date'],
      dtype='str')

In [11]:
df.isnull().sum()

Invoice_ID         0
Date               0
Medicine_Name      0
Category           0
Quantity           0
Unit_Price         0
Revenue            0
Profit             0
Customer_Type      0
Branch             0
Payment_Method     0
Stock_Available    0
Expiry_Date        0
dtype: int64

In [12]:
df.describe()

          Quantity   Unit_Price       Revenue       Profit  Stock_Available
count  2000.000000  2000.000000   2000.000000  2000.000000      2000.000000
mean     10.554000   765.348565   8142.985355  1835.850525       261.288000
std       5.706783   425.033929   6794.965394  1714.017184       141.438515
min       1.000000    21.750000     32.380000     5.910000        10.000000
25%       5.750000   404.522500   2458.425000   512.902500       138.000000
50%      11.000000   760.720000   6306.685000  1318.650000       262.000000
75%      15.000000  1137.510000  12320.895000  2684.995000       385.000000
max      20.000000  1499.730000  29594.800000  9010.400000       500.000000

In [13]:
# Convert Date column into datetime
df['Date'] = pd.to_datetime(df['Date'])

C:\Users\abpaw\AppData\Local\Temp\ipykernel_23592\2883493258.py:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Date'] = pd.to_datetime(df['Date'])

In [14]:
# Create Month column
df['Month'] = df['Date'].dt.month_name()

In [15]:
df

,Invoice_ID,Date,Medicine_Name,Category,Quantity,Unit_Price,Revenue,Profit,Customer_Type,Branch,Payment_Method,Stock_Available,Expiry_Date,Month
0,INV00001,2024-04-16,Omeprazole,Vitamin,11,994.95,10944.45,2705.68,New,Hyderabad,Cash,376,07-05-2025,April
1,INV00002,2025-04-15,Omeprazole,Antibiotic,4,401.28,1605.12,201.31,New,Pune,UPI,163,19-04-2026,April
2,INV00003,2024-10-20,Azithromycin,Diabetes,18,733.21,13197.78,4196.14,Regular,Pune,Cash,129,27-02-2026,October
3,INV00004,2024-04-02,Calcium Tablets,Antacid,18,181.13,3260.34,372.62,New,Mumbai,UPI,376,02-01-2026,April
4,INV00005,2025-04-09,Aspirin,Cold & Flu,11,611.62,6727.82,1844.97,Regular,Hyderabad,UPI,24,13-03-2027,April
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,INV01996,2024-12-27,Azithromycin,Cold & Flu,17,1177.48,20017.16,3036.10,New,Hyderabad,Card,224,19-06-2026,December
1996,INV01997,2024-04-30,Cetirizine,Painkiller,3,351.23,1053.69,244.79,Regular,Hyderabad,Card,417,15-08-2024,April
1997,INV01998,2025-04-30,Paracetamol,Antacid,2,105.15,210.30,39.45,Regular,Bangalore,Cash,100,26-01-2027,April
1998,INV01999,2024-01-28,Cetirizine,Painkiller,12,1486.38,17836.56,5517.13,Regular,Bangalore,Card,113,18-05-2024,January
1999,INV02000,2025-03-15,Cetirizine,Vitamin,10,30.02,300.20,50.62,New,Pune,Cash,308,15-01-2027,March

In [17]:
# Total Revenue
total_revenue = df['Revenue'].sum()
print(total_revenue)

16285970.71

In [19]:
# Total Profit
total_profit = df['Profit'].sum()
print(total_profit)

3671701.05

In [20]:
# Total Quantity Sold
total_quantity = df['Quantity'].sum()
print(total_quantity)

21108

In [21]:
# Average Revenue
average_revenue = df['Revenue'].mean()
print(average_revenue)

8142.985355000001

In [25]:
#Top selling medicines.
top_medicines = (df.groupby('Medicine_Name')['Revenue'].sum().sort_values(ascending=False))
print(top_medicines.head())

Medicine_Name
Metformin      1311624.81
Dolo 650       1309597.94
Amoxicillin    1278967.18
Cough Syrup    1155275.45
Paracetamol    1128119.42
Name: Revenue, dtype: float64

In [24]:
#monthly sales trend
monthly_sales = ( df.groupby(df['Date'].dt.month)['Revenue'].sum())
print(monthly_sales)

Date
1     1893213.20
2     1712059.24
3     2046924.51
4     1956699.01
5     1501089.53
6     1090112.28
7      967238.87
8     1170423.71
9      957981.71
10    1184014.19
11     963741.69
12     842472.77
Name: Revenue, dtype: float64

In [26]:
df.to_csv("cleaned_pharmacy_sales.csv", index=False)
print("Cleaned dataset saved successfully")

Cleaned dataset saved successfully